# This workflow will install Python dependencies and run the validate.py script to ensure all reviews are complete.

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Run validator
    #   run: |
    #     # stop the build if there are any errors (errcode 0 means 'pass')
    #     python validate.py
    - name: Generate overview
      run: |
        # stop the build if there are any errors (errcode 0 means 'pass')
        python generate_overview.py
    - name: setup git config
      run: |
        git config user.name ${{ secrets.USERNAME }}
        git config user.email ${{ secrets.EMAIL }}
    - name: Set permission
      run: |
        sudo chmod +x ./overview.md
    - name: Commit changes
      run: |
        chmod +x ./sync_overview.sh
        ./sync_overview.sh
