# This workflow will install Python dependencies and run the validate.py script to ensure all reviews are complete.

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./scripts/requirements/requirements.txt ]; then pip install -r ./scripts/requirements/requirements.txt; fi
    - name: Run validator
      run: |
        # stop the build if there are any errors (errcode 0 means 'pass')
        python ./scripts/validate.py
